server:
  port: 9013

spring:
  application:
    name: log-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring_examples_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password:
    hikari:
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS

logging:
  level.root: info
  file: /temp/ebid-cloud/ebid-user-log/ebid-user-server.log
  file.max-size: 10MB
  file.max-history: 730